'use client';
import {useEffect,useMemo,useState} from 'react';

const STORES=['ALDI','Walmart','Trader Joe’s','Stater Bros.','Vons','Ralphs','Sprouts','Food 4 Less','Costco'];
const PRODUCTS=[
{id:11,name:'Friendly Farms Nonfat Plain Greek Yogurt',size:'32 oz',store:'ALDI',price:2.79,protein:17,fiber:0,plants:0,calcium:2,prep:0,img:'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_e1687237-629e-499a-b213-e40fae5b59ec.jpg',source:'OFFICIAL PRICE'},
{id:13,name:'Kirkwood Fresh Chicken Breast Family Pack',size:'per lb',store:'ALDI',price:12.70,protein:4,fiber:0,plants:0,calcium:0,prep:15,img:'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_d2a89978-895b-42cc-8dd6-bd93edb3d246.jpg',source:'OFFICIAL PRICE'},
{id:8,name:'Greek Lowfat Yogurt Plain',size:'16 oz',store:'Trader Joe’s',price:2.99,protein:16,fiber:0,plants:0,calcium:2,prep:0,img:'https://www.traderjoes.com/content/dam/trjo/products/m20303/86453.png',source:'OFFICIAL PRICE'},
{id:101,name:'Great Value Boneless Skinless Chicken Breasts',size:'3 lb',store:'Walmart',price:9.47,protein:4,fiber:0,plants:0,calcium:0,prep:15,img:'https://i5.walmartimages.com/seo/Great-Value-All-Natural-Boneless-Skinless-Chicken-Breasts-3-lb-Frozen_e24ab2b0-b88c-490e-ae8c-45b16e51bfcd.acf916b110711d4c5c846216b635c615.jpeg?odnBg=FFFFFF&odnHeight=573&odnWidth=573',source:'OFFICIAL PRICE'},
{id:3,name:'Minute Instant White Rice',size:'14 oz',store:'Walmart',price:5.97,protein:1,fiber:1,plants:0,calcium:0,prep:5,img:'https://i5.walmartimages.com/asr/2ffbeccf-cd1a-4a5d-93dc-bb3f0e345d30.6b37a3fc5c09fdceac7d24b4b0e30114.jpeg',source:'ESTIMATED'},
{id:15,name:'SunVista Black Beans',size:'15 oz',store:'Stater Bros.',price:1.29,protein:2,fiber:4,plants:3,calcium:0,prep:2,img:'https://images.albertsons-media.com/is/image/ABS/960075954',source:'LOCAL DELIVERY PRICE'},
{id:102,name:'Large Grade A Eggs',size:'12 ct',store:'ALDI',price:3.97,protein:3,fiber:0,plants:0,calcium:0,prep:8,img:'https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_444fa62a-70a7-48e4-8db6-c25f37ab4c8f.jpg',source:'ESTIMATED'},
{id:103,name:'Mixed Vegetables',size:'12 oz',store:'Stater Bros.',price:2.49,protein:1,fiber:3,plants:4,calcium:0,prep:5,img:'https://images.albertsons-media.com/is/image/ABS/960031312',source:'ESTIMATED'}];
const STEPS=['goal','budget','life','equipment','food','stores','optimize'];
const defaults={goals:['eat better','save money'],budget:70,people:1,meals:10,cook:'10',microwave:false,stove:true,oven:false,airfryer:true,fridge:true,freezer:true,portable:true,reheatAway:false,cold:true,dislikes:'',stores:['ALDI','Walmart'],maxStores:2,mode:'balance'};

function load(k,f){if(typeof window==='undefined')return f;try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function money(n){return '$'+Number(n||0).toFixed(2)}

export default function Page(){
 const [profile,setProfile]=useState(null),[step,setStep]=useState(0),[p,setP]=useState(defaults),[tab,setTab]=useState('home'),[bought,setBought]=useState([]),[skipped,setSkipped]=useState([]),[priceEdit,setPriceEdit]=useState(null),[reports,setReports]=useState({});
 useEffect(()=>{setProfile(load('ff_profile',null));setP(load('ff_preferences',defaults));setBought(load('ff_bought',[]));setReports(load('ff_prices',{}))},[]);
 const save=(k,v)=>{localStorage.setItem(k,JSON.stringify(v))};
 const update=(key,val)=>setP(x=>({...x,[key]:val}));
 const toggle=(key,val)=>update(key,p[key].includes(val)?p[key].filter(x=>x!==val):[...p[key],val]);
 const scored=useMemo(()=>PRODUCTS.map(x=>{let score=50;if(p.stores.includes(x.store))score+=25;if(x.prep<=Number(p.cook))score+=20;if(p.goals.includes('more protein'))score+=x.protein;if(p.goals.includes('eat better'))score+=x.fiber+x.plants;if(p.mode==='cheap')score-=x.price;return {...x,score,shownPrice:reports[x.id]?.price??x.price,shownSource:reports[x.id]?'COMMUNITY UPDATED':x.source}}).filter(x=>!skipped.includes(x.id)).sort((a,b)=>b.score-a.score),[p,reports,skipped]);
 const plan=scored.slice(0,Math.min(8,Math.max(5,p.meals)));
 const open=plan.filter(x=>!bought.includes(x.id));
 const total=plan.reduce((s,x)=>s+Number(x.shownPrice),0);
 const mark=id=>{let n=bought.includes(id)?bought.filter(x=>x!==id):[...bought,id];setBought(n);save('ff_bought',n)};
 const finish=()=>{save('ff_preferences',p);save('ff_profile',{name:'freshfresh user',createdAt:new Date().toISOString()});setProfile({name:'freshfresh user'});setTab('home')};
 if(!profile)return <Onboard step={step} setStep={setStep} p={p} update={update} toggle={toggle} finish={finish}/>;
 const submitPrice=(id,val)=>{const next={...reports,[id]:{price:Number(val),at:new Date().toISOString(),verified:false}};setReports(next);save('ff_prices',next);setPriceEdit(null)};
 return <main className="app"><header className="top"><div className="brand">freshfresh<span className="logoDot"/></div><span className="eyebrow">WEEK 01 · SMART PLAN</span></header>
 {tab==='home'&&<><div className="eyebrow">YOUR REAL-LIFE FOOD SYSTEM</div><h1 className="hero">Eat better.<br/>Live easier.</h1><p className="sub">Built around your budget, time, kitchen and actual routine. Not a strict diet.</p><div className="summary"><div className="stat"><b>{money(p.budget)}</b><span className="eyebrow">budget</span></div><div className="stat"><b>{money(total)}</b><span className="eyebrow">plan</span></div><div className="stat"><b>{open.length}</b><span className="eyebrow">open</span></div></div><section className="card"><div className="row"><div><div className="eyebrow">FRESH INTELLIGENCE</div><b>{p.cook==='0'?'No-cook week':`≤ ${p.cook} min cooking`}</b></div><span className="best">LIVE PROFILE</span></div><p className="sub">{p.portable?'Portable meals prioritized. ':''}{!p.microwave?'No microwave assumed. ':''}{p.maxStores} store max · {p.mode==='cheap'?'cheapest possible':p.mode==='one'?'one store':'best balance'}.</p></section><button className="btn lime" onClick={()=>setTab('shop')}>START SHOPPING →</button></>}
 {tab==='shop'&&<Shop item={open[0]} left={open.length} mark={mark} skip={id=>setSkipped(x=>[...x,id])} edit={setPriceEdit}/>} 
 {tab==='list'&&<List plan={plan} bought={bought} mark={mark} edit={setPriceEdit}/>} 
 {tab==='nutrition'&&<Nutrition plan={plan}/>} 
 {tab==='profile'&&<Profile p={p} reset={()=>{localStorage.removeItem('ff_profile');setProfile(null);setStep(0)}}/>}
 <nav className="nav">{[['home','HOME'],['shop','SHOP'],['list','LIST'],['nutrition','BLOCKS'],['profile','YOU']].map(([k,l])=><button key={k} className={tab===k?'on':''} onClick={()=>setTab(k)}>{l}</button>)}</nav>
 {priceEdit&&<PriceSheet item={priceEdit} close={()=>setPriceEdit(null)} submit={submitPrice}/>}</main>
}

function Onboard({step,setStep,p,update,toggle,finish}){const s=STEPS[step],next=()=>step===STEPS.length-1?finish():setStep(step+1);return <main className="app onboard"><div className="top"><div className="brand">freshfresh<span className="logoDot"/></div><span className="eyebrow">{step+1}/{STEPS.length}</span></div><div className="progress"><i style={{width:`${(step+1)/STEPS.length*100}%`}}/></div>
 {s==='goal'&&<Step title="What should food do for you?" sub="Pick everything that matters. There is no diet mode."><Choices vals={['eat better','save money','save time','more protein','more variety','less decisions']} selected={p.goals} on={v=>toggle('goals',v)}/></Step>}
 {s==='budget'&&<Step title="What does a normal week look like?" sub="We optimize around the money you actually want to spend."><label className="eyebrow">WEEKLY BUDGET</label><input className="input" type="number" value={p.budget} onChange={e=>update('budget',+e.target.value)}/><div className="choices"><Num label="people" v={p.people} set={v=>update('people',v)}/><Num label="meals to solve" v={p.meals} set={v=>update('meals',v)}/></div></Step>}
 {s==='life'&&<Step title="How much do you want to cook?" sub="Zero is a valid answer. freshfresh adapts."><Choices vals={['0','5','10','15','30']} selected={[p.cook]} format={v=>v==='0'?'Basically none':`${v} min max`} on={v=>update('cook',v)}/><Toggle label="I need meals I can take with me" on={p.portable} set={v=>update('portable',v)}/><Toggle label="I can eat some meals cold" on={p.cold} set={v=>update('cold',v)}/><Toggle label="I can reheat away from home" on={p.reheatAway} set={v=>update('reheatAway',v)}/></Step>}
 {s==='equipment'&&<Step title="What can you actually use?" sub="We will not recommend microwave meals if there is no microwave.">{[['microwave','Microwave'],['stove','Stove'],['oven','Oven'],['airfryer','Air fryer'],['fridge','Fridge'],['freezer','Freezer']].map(([k,l])=><Toggle key={k} label={l} on={p[k]} set={v=>update(k,v)}/>)}</Step>}
 {s==='food'&&<Step title="Anything you just don’t want?" sub="Taste matters. Better food only works if you actually want to eat it."><textarea className="input" rows="5" placeholder="Example: avocado, shrimp, plain salads..." value={p.dislikes} onChange={e=>update('dislikes',e.target.value)}/></Step>}
 {s==='stores'&&<Step title="Where are you willing to shop?" sub="Pick stores you actually use. You can change this anytime."><Choices vals={STORES} selected={p.stores} on={v=>toggle('stores',v)}/><label className="eyebrow">MAX STORES THIS WEEK · {p.maxStores}</label><input className="range" type="range" min="1" max="3" value={p.maxStores} onChange={e=>update('maxStores',+e.target.value)}/></Step>}
 {s==='optimize'&&<Step title="What should we optimize first?" sub="Saving $2 is not always worth another 20-minute stop."><Choices vals={['cheap','balance','one']} selected={[p.mode]} format={v=>({cheap:'Cheapest possible',balance:'Best balance',one:'One store only'}[v])} on={v=>update('mode',v)}/><div className="notice">Your plan will consider price + time + effort + taste + nutrient coverage + store count.</div></Step>}
 <div className="row" style={{marginTop:24}}>{step>0?<button className="btn alt" onClick={()=>setStep(step-1)}>BACK</button>:<span/>}<button className="btn lime" onClick={next}>{step===STEPS.length-1?'BUILD MY WEEK →':'CONTINUE →'}</button></div></main>}
function Step({title,sub,children}){return <section><h1 className="hero" style={{fontSize:36,marginTop:28}}>{title}</h1><p className="sub">{sub}</p><div className="stack">{children}</div></section>}
function Choices({vals,selected,on,format=v=>v}){return <div className="choices">{vals.map(v=><button key={v} className={'choice '+(selected.includes(v)?'on':'')} onClick={()=>on(v)}>{format(v)}</button>)}</div>}
function Toggle({label,on,set}){return <button className={'choice row '+(on?'on':'')} onClick={()=>set(!on)}><span>{label}</span><b>{on?'YES':'NO'}</b></button>}
function Num({label,v,set}){return <div className="card soft"><div className="eyebrow">{label}</div><div className="row"><button className="btn sm alt" onClick={()=>set(Math.max(1,v-1))}>−</button><b>{v}</b><button className="btn sm alt" onClick={()=>set(v+1)}>+</button></div></div>}
function Shop({item,left,mark,skip,edit}){if(!item)return <><h2 className="hero">Cart handled.</h2><p className="sub">Everything in this plan is marked bought.</p></>;return <section className="product"><div><div className="row"><span className="eyebrow">SHOPPING MODE · {left} OPEN</span><span className="best">BEST MATCH</span></div><div className="photo"><img src={item.img} alt={item.name}/></div><div className="eyebrow">{item.store} · {item.size}</div><h2 className="sectionTitle">{item.name}</h2><div className="row"><span className="price">{money(item.shownPrice)}</span><span className="tag">{item.shownSource}</span></div><p className="meta">{item.protein} protein block score · {item.prep} min prep</p><button className="btn sm alt" onClick={()=>edit(item)}>UPDATE PRICE</button></div><div className="actions"><button className="btn alt" onClick={()=>skip(item.id)}>SKIP</button><button className="btn lime" onClick={()=>mark(item.id)}>✓ GOT IT</button></div></section>}
function List({plan,bought,mark,edit}){return <><div className="eyebrow">YOUR WEEK</div><h1 className="hero">Shopping list.</h1>{plan.map(x=><div className={'listitem '+(bought.includes(x.id)?'bought':'')} key={x.id}><img className="thumb" src={x.img} alt=""/><div onClick={()=>mark(x.id)}><b>{x.name}</b><div className="eyebrow">{x.store} · {x.size} · {x.shownSource}</div></div><div style={{textAlign:'right'}}><b>{money(x.shownPrice)}</b><br/><button className="btn sm alt" onClick={()=>edit(x)}>PRICE</button></div></div>)}</>}
function Nutrition({plan}){const raw={protein:plan.reduce((s,x)=>s+x.protein,0),plants:plan.reduce((s,x)=>s+x.plants,0),fiber:plan.reduce((s,x)=>s+x.fiber,0),calcium:plan.reduce((s,x)=>s+x.calcium,0),variety:new Set(plan.map(x=>x.name.split(' ')[0])).size};const blocks=[['PROTEIN',raw.protein,28],['PLANTS',raw.plants,16],['FIBER',raw.fiber,16],['CALCIUM',raw.calcium,8],['VARIETY',raw.variety,6]];return <><div className="eyebrow">NO CALORIE OBSESSION</div><h1 className="hero">Nutrition<br/>coverage.</h1><p className="sub">Blocks show where your week is strong and where one simple grocery swap can improve coverage.</p><div className="blocks">{blocks.map(([l,v,t])=><div className="blockline" key={l}><span className="eyebrow">{l}</span><div className="meter"><i style={{width:`${Math.min(100,v/t*100)}%`}}/></div><b>{Math.min(4,Math.ceil(v/t*4))}/4</b></div>)}</div><div className="card"><b>Your next easy win</b><p className="sub">Add a fiber + plant food such as beans or frozen vegetables when those blocks are low. The goal is a better week, not a perfect score.</p></div></>}
function Profile({p,reset}){return <><div className="eyebrow">HOW YOU ACTUALLY LIVE</div><h1 className="hero">Your food<br/>profile.</h1><div className="card"><p><b>{money(p.budget)}</b> weekly · {p.people} person · {p.meals} meals</p><p>Cooking: <b>{p.cook==='0'?'basically none':p.cook+' min max'}</b></p><p>Microwave: <b>{p.microwave?'yes':'no'}</b> · Air fryer: <b>{p.airfryer?'yes':'no'}</b></p><p>Portable meals: <b>{p.portable?'yes':'no'}</b></p><p>Stores: <b>{p.stores.join(', ')}</b></p></div><button className="btn alt" onClick={reset}>RETAKE ONBOARDING</button></>}
function PriceSheet({item,close,submit}){const [v,setV]=useState(item.shownPrice);return <div className="modal" onClick={close}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="eyebrow">COMMUNITY PRICE · {item.store}</div><h2 className="sectionTitle">Update what you see in store.</h2><p className="sub">Enter the shelf price for this exact package. Photo/receipt verification comes next.</p><input className="input" autoFocus type="number" step="0.01" value={v} onChange={e=>setV(e.target.value)}/><div className="notice" style={{margin:'12px 0'}}>This report is saved with a timestamp and shown as COMMUNITY UPDATED. It does not silently overwrite an official price.</div><div className="actions"><button className="btn alt" onClick={close}>CANCEL</button><button className="btn lime" onClick={()=>submit(item.id,v)}>SAVE PRICE</button></div></div></div>}
